### ISSUE TITLE
Client crash: NPE on disconnecting from MP server with radio playing

### ISSUE THREAD

**Issue by gdude2002** [PC-Logix/OpenFM#52] opened 2016-12-21 18:51 UTC
```
java.lang.NullPointerException: Updating screen events
	at pcl.OpenFM.player.MP3Player.createEvent(MP3Player.java:185)
	at pcl.OpenFM.player.MP3Player.createEvent(MP3Player.java:181)
	at pcl.OpenFM.player.MP3Player.stop(MP3Player.java:197)
	at pcl.OpenFM.player.PlayerDispatcher.stop(PlayerDispatcher.java:89)
	at pcl.OpenFM.OpenFM.killAllStreams(OpenFM.java:97)
	at pcl.OpenFM.Handler.ClientEvent.worldUnload(ClientEvent.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_773_ClientEvent_worldUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2364)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
	at net.minecraft.client.gui.GuiIngameMenu.func_146284_a(GuiIngameMenu.java:52)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CaitlynMainer** [comment] 2016-12-21 18:57
MC/OFM Version? ( Guess I could have asked for this in #OC Huh..)

**Comment by gdude2002** [comment] 2016-12-21 19:00
Oh, sorry. Totally forgot.

MC: 1.10.2
Forge: 12.18.3.2185
OFM: 0.1.0.18

**Comment by CaitlynMainer** [comment] 2016-12-22 03:02
I can't reproduce this, is there anything preceding this in the client log, or anything related in the server log?

**Comment by gdude2002** [comment] 2016-12-22 09:56
Well, here's the [crash log](https://github.com/PC-Logix/OpenFM/files/668471/crash-2016-12-21_22.45.51-client.txt). I don't have a console output from this currently as I'm kinda busy today, but I can probably grab it later on.

**Comment by gdude2002** [comment] 2016-12-22 12:04
This is what appears just before the log.

```
[12:03:04] [Client thread/INFO] [openfm]: Stopping all currently running radio streams.
[12:03:04] [Client thread/INFO] [openfm]: Stopping all currently running radio streams.
[12:03:04] [Client thread/INFO] [journeymap]: Mapping halted in C:\Users\-gdude2002\Desktop\SKCraft\Launcher-master\launcher\build\libs\.\instances\Mystic (Casual)\minecraft\journeymap\data\mp\Mystic~Minecraft\DIM0
[12:03:04] [Client thread/INFO] [FML]: Applying holder lookups
[12:03:04] [Client thread/INFO] [FML]: Holder lookups applied
[12:03:12] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1713) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at pcl.OpenFM.player.MP3Player.createEvent(MP3Player.java:185) ~[MP3Player.class:?]
	at pcl.OpenFM.player.MP3Player.createEvent(MP3Player.java:181) ~[MP3Player.class:?]
	at pcl.OpenFM.player.MP3Player.stop(MP3Player.java:197) ~[MP3Player.class:?]
	at pcl.OpenFM.player.PlayerDispatcher.stop(PlayerDispatcher.java:89) ~[PlayerDispatcher.class:?]
	at pcl.OpenFM.OpenFM.killAllStreams(OpenFM.java:97) ~[OpenFM.class:?]
	at pcl.OpenFM.Handler.ClientEvent.worldUnload(ClientEvent.java:16) ~[ClientEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_773_ClientEvent_worldUnload_Unload.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2364) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) ~[bcx.class:?]
	at net.minecraft.client.gui.GuiIngameMenu.func_146284_a(GuiIngameMenu.java:52) ~[bfp.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460) ~[bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) ~[bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) ~[bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) ~[bcx.class:?]
	... 9 more
[12:03:12] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
```

**Comment by gdude2002** [comment] 2016-12-22 12:05
This is specifically when clicking the disconnect button in the esc menu; it doesn't happen if the server kicks me

**Comment by CaitlynMainer** [comment] 2016-12-22 12:45
http://michi.pc-logix.com/2016-12-22_06-44-08.mp4  I can't reproduce this issue in dev, or in prod.

**Comment by gdude2002** [comment] 2016-12-22 12:47
Are you using a different version of Forge?

**Comment by CaitlynMainer** [comment] 2016-12-22 19:13
I'm still unable to reproduce this on that exact version of forge, you mentioned FoamFix as a possibility?

**Comment by gdude2002** [comment] 2016-12-22 19:14
Yeah, I'll have to bonk asie on the noggin and see what he thinks.

It's a mod (optionally a coremod) which does a bunch of optimisations relating to memory.

**Comment by gdude2002** [comment] 2016-12-22 19:14
Site's here - http://asie.pl/foamfix/

**Comment by CaitlynMainer** [comment] 2016-12-22 19:16
And you're using Lawful or Anarchy edition?

**Comment by gdude2002** [comment] 2016-12-22 19:19
Anarchy at the moment

**Comment by CaitlynMainer** [comment] 2016-12-22 19:20
I'll test with that tonight after Naomi's Birthday dinner.

**Comment by gdude2002** [comment] 2016-12-22 19:27
Thanks, I'd do it myself but I'm not gonna be at that machine for some time

**Comment by CaitlynMainer** [comment] 2016-12-23 02:15
I'm still unable to reproduce this, running FoamFix Anarchy and OpenFM 18

**Comment by gdude2002** [comment] 2016-12-23 11:32
Hmm, maybe you inadvertently fixed it. Well, don't worry about it for now, then - I'll take a deeper look another time.

**Comment by CaitlynMainer** [comment] 2016-12-23 14:51
It's unlikely that I've fixed it, since I tested it with the current release from curse.

**Comment by gdude2002** [comment] 2016-12-23 22:15
Well, is there anything else I can check out for you? Would it be better to give you access to the server that goes with [our modpack](https://mc.pokemongomystic.com/download/)?

**Comment by gdude2002** [comment] 2017-01-11 17:46
I am no longer able to reproduce this for some reason.

**Comment by CaitlynMainer** [comment] 2017-01-11 18:26
Going to close this then, feel free to re-open if you find more info.

**Closed by CaitlynMainer** 2017-01-11 18:26 UTC
