### ISSUE TITLE
OGG streams don't play

### ISSUE THREAD

**Issue by Teteros** [PC-Logix/OpenFM#33] opened 2016-02-28 04:34 UTC
Version tried: [OpenFM-1.7.10-0.1.0-29.jar](http://www.curse.com/mc-mods/minecraft/236839-openfm/2278934),
alone or with OpenComputers.

OGG streams don't seem to be detected at all, only MP3 streams are.
Nothing in logs when the play button is pressed, not even an invalid link message.

The strange thing is: OGG streams work perfectly fine if I launch the client in the dev environment. (via runClient gradle task, for example)

Used my MPD httpd server and [Xiph's icecast directory](http://dir.xiph.org/by_format/Ogg_Vorbis), for testing OGG streams.

**Comment by CaitlynMainer** [comment] 2016-03-16 02:00
I can't reproduce this, http://stream.radioreklama.bg:80/nrj.ogg and a few others worked fine for me.  Make sure you have the mp3 and ogg spi files in your /mods/1.7.10/ directory

**Comment by CaitlynMainer** [comment] 2016-03-16 02:28
Nevermind I was able to reproduce this, for some reason ogg streams get marked as invalid.. I'll investigate

**Closed** 2016-03-16 04:10 UTC
